#!/bin/sh
#
#  Copyright © 2020 Mark Raynsford <code@io7m.com> https://www.io7m.com
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
#  SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
#  IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

fatal()
{
  echo "waxmill: fatal: $1" 1>&2
  exit 1
}

if [ -z "${WAXMILL_HOME}" ]
then
  fatal "WAXMILL_HOME is not defined"
fi

if [ -z "${WAXMILL_JAR_NAME}" ]
then
  WAXMILL_JAR_NAME="waxmill.jar"
fi

WAXMILL_JAR_FILE="${WAXMILL_HOME}/${WAXMILL_JAR_NAME}"

exec java -jar "${WAXMILL_JAR_FILE}" "$@"